import { env } from './env';

export const FEATURE_PUBMED_SEARCH = env.FEATURE_PUBMED_SEARCH;
export const FEATURE_PUBMED_IMPORT = env.FEATURE_PUBMED_IMPORT;
export const FEATURE_PUBMED_EFETCH = env.FEATURE_PUBMED_EFETCH;
export const ENABLE_PUBMED_WORKER = env.ENABLE_PUBMED_WORKER;

export const PUBMED = {
  BASE: env.PUBMED_API_BASE,
  TOOL: env.PUBMED_TOOL_NAME,
  EMAIL: env.PUBMED_EMAIL || "",
  API_KEY: env.PUBMED_API_KEY || "",
  RPS: env.PUBMED_RATE_LIMIT_RPS,
  SUMMARY_CACHE_TTL_SEC: env.PUBMED_SUMMARY_CACHE_TTL_SEC
};

